# Pages placed under these sections will be shown on homepage and archive page.
mainSections = ["post"]
# Output page's full content in RSS.
rssFullContent = true
favicon = "/favicon.png"

[footer]
customText = "My heart is in the work â€• Andrew Carnegie"

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 EST"

[sidebar]
emoji = "ðŸ’•"
subtitle = "mia Â· pgh Â· nyc"

[sidebar.avatar]
enabled = true
local = true
src = "img/github_rose.jpeg"

[article]
math = true
readingTime = true

## Widgets
[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"

[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"

[widgets.homepage.params]
limit = 10

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = false
default = "dark"

[imageProcessing.cover]
enabled = true

[imageProcessing.content]
enabled = true
